/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.view;


import java.io.File;
import javax.swing.*;





/**
 *
 * @author chengqian
 */
public class TeacherManagePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form TeacherManagePanel
     */
    public TeacherManagePanel() {
        initComponents();
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setAutoCreateColumnsFromModel(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refreshTableButton = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        importTableButton = new javax.swing.JButton();
        exportTableButton = new javax.swing.JButton();
        searchPanel = new org.jdesktop.swingx.JXSearchPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 38));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        refreshTableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh-24.png"))); // NOI18N
        refreshTableButton.setText("Refresh");
        refreshTableButton.setMargin(new java.awt.Insets(0, 2, 0, 8));
        refreshTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTableButtonActionPerformed(evt);
            }
        });
        jPanel1.add(refreshTableButton);

        addStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-24.png"))); // NOI18N
        addStudentButton.setText("Add");
        addStudentButton.setMargin(new java.awt.Insets(0, 2, 0, 8));
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addStudentButton);

        importTableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/import-24.png"))); // NOI18N
        importTableButton.setText("Import");
        importTableButton.setMargin(new java.awt.Insets(0, 2, 0, 8));
        importTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importTableButtonActionPerformed(evt);
            }
        });
        jPanel1.add(importTableButton);

        exportTableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/down-24.png"))); // NOI18N
        exportTableButton.setText("Export");
        exportTableButton.setMargin(new java.awt.Insets(0, 2, 0, 8));
        exportTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportTableButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exportTableButton);

        searchPanel.setMinimumSize(new java.awt.Dimension(485, 37));
        searchPanel.setName(""); // NOI18N
        jPanel1.add(searchPanel);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+13));
        jLabel1.setText("Teacher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void importTableButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_importTableButtonActionPerformed
        // TODO add your handling code here:
    /*
    if (isCsv(file.getAbsolutePath())) {  
            CsvReader reader = new CsvReader(filePath, ',', Charset.forName("GBK"));  
            reader.readHeaders();   
            while (reader.readRecord()) {  
                tableModel.add(reader.getValues());  
            }  
            reader.close();  
        } else {  
            System.out.println("此文件不是CSV文件！");  
        }
    
    CSVReader reader = new CSVReader(new FileReader(jfc.getSelectedFile().getName())); 
    List myEntries = reader.readAll();
    JTable table = new JTable(myEntries.toArray());
    */
    }//GEN-LAST:event_importTableButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void exportTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportTableButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportTableButtonActionPerformed

    private void refreshTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTableButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshTableButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addStudentButton;
    public javax.swing.JButton exportTableButton;
    public javax.swing.JButton importTableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton refreshTableButton;
    public org.jdesktop.swingx.JXSearchPanel searchPanel;
    public org.jdesktop.swingx.JXTable table;
    // End of variables declaration//GEN-END:variables

    
}
